import React, { useState } from 'react';
import { Invoice, CompanySettings, formatINR, GSTSummaryItem, TaxSlab } from '../types';
import { 
  Printer, Download, X, Copy, Check, Share2, FileText, CheckCircle2, ShieldCheck, QrCode
} from 'lucide-react';

interface SalesBillPrintModalProps {
  invoice: Invoice;
  settings: CompanySettings;
  onClose: () => void;
}

// Convert numbers into Indian Currency words
function numberToWordsINR(amount: number): string {
  const rounded = Math.round(amount);
  if (rounded === 0) return 'Zero Rupees Only';

  const singleDigits = ['', 'One', 'Two', 'Three', 'Four', 'Five', 'Six', 'Seven', 'Eight', 'Nine'];
  const teens = ['Ten', 'Eleven', 'Twelve', 'Thirteen', 'Fourteen', 'Fifteen', 'Sixteen', 'Seventeen', 'Eighteen', 'Nineteen'];
  const tens = ['', '', 'Twenty', 'Thirty', 'Forty', 'Fifty', 'Sixty', 'Seventy', 'Eighty', 'Ninety'];

  function convertTwoDigits(n: number): string {
    if (n < 10) return singleDigits[n];
    if (n >= 10 && n < 20) return teens[n - 10];
    const ten = Math.floor(n / 10);
    const unit = n % 10;
    return tens[ten] + (unit ? ' ' + singleDigits[unit] : '');
  }

  function convertThreeDigits(n: number): string {
    const hundred = Math.floor(n / 100);
    const rest = n % 100;
    let str = '';
    if (hundred) {
      str += singleDigits[hundred] + ' Hundred';
      if (rest) str += ' and ';
    }
    if (rest) {
      str += convertTwoDigits(rest);
    }
    return str;
  }

  let num = rounded;
  let words = '';

  const crore = Math.floor(num / 10000000);
  num %= 10000000;
  if (crore) {
    words += convertTwoDigits(crore) + ' Crore ';
  }

  const lakh = Math.floor(num / 100000);
  num %= 100000;
  if (lakh) {
    words += convertTwoDigits(lakh) + ' Lakh ';
  }

  const thousand = Math.floor(num / 1000);
  num %= 1000;
  if (thousand) {
    words += convertTwoDigits(thousand) + ' Thousand ';
  }

  if (num) {
    words += convertThreeDigits(num);
  }

  return 'Rupees ' + words.trim() + ' Only';
}

export const SalesBillPrintModal: React.FC<SalesBillPrintModalProps> = ({
  invoice,
  settings,
  onClose
}) => {
  const [copyType, setCopyType] = useState<'Original' | 'Duplicate' | 'Triplicate'>('Original');
  const [copied, setCopied] = useState(false);

  const isInterState = invoice.taxType === 'inter_state' || invoice.igstAmount > 0;

  // Rate-wise GST Summary calculation
  const gstRateSummaries = React.useMemo(() => {
    const map = new Map<string, GSTSummaryItem>();

    if (invoice.items && invoice.items.length > 0) {
      invoice.items.forEach(item => {
        const slab: TaxSlab = (item.gstRate !== undefined ? item.gstRate : invoice.taxSlab) || 0;
        const key = `${item.hsnCode || '2523'}_${slab}`;
        const taxable = item.taxableAmount || (item.quantity * (item.rate || (item.amount / item.quantity)));

        if (!map.has(key)) {
          const halfRate = isInterState ? 0 : slab / 2;
          const fullRate = isInterState ? slab : 0;
          map.set(key, {
            hsnCode: item.hsnCode || '—',
            gstRate: slab,
            taxableValue: 0,
            cgstRate: halfRate,
            cgstAmount: 0,
            sgstRate: halfRate,
            sgstAmount: 0,
            igstRate: fullRate,
            igstAmount: 0,
            totalTax: 0
          });
        }

        const curr = map.get(key)!;
        curr.taxableValue += taxable;

        if (isInterState) {
          curr.igstAmount += (taxable * slab) / 100;
        } else {
          curr.cgstAmount += (taxable * (slab / 2)) / 100;
          curr.sgstAmount += (taxable * (slab / 2)) / 100;
        }
        curr.totalTax = curr.cgstAmount + curr.sgstAmount + curr.igstAmount;
      });
    }

    return Array.from(map.values());
  }, [invoice, isInterState]);

  const handlePrint = () => {
    window.print();
  };

  const handleCopySummary = () => {
    const text = `*TAX INVOICE / SALES BILL*\nBill No: ${invoice.salesBillNumber || invoice.invoiceNumber}\nDate: ${invoice.salesBillDate || invoice.invoiceDate}\nParty: ${invoice.consignorName || invoice.consigneeName}\nGSTIN: ${invoice.consignorGSTIN || invoice.consigneeGSTIN || 'N/A'}\nGrand Total: ₹${formatINR(invoice.grandTotal)}\nBalance Due: ₹${formatINR(invoice.balanceDue)}\n\n_Generated by ${settings.companyName}_`;
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  // UPI payment QR link
  const upiPayUrl = `upi://pay?pa=${encodeURIComponent(settings.upiId || '9687709315@upi')}&pn=${encodeURIComponent(settings.companyName)}&am=${invoice.balanceDue}&cu=INR&tn=${encodeURIComponent(`Bill ${invoice.salesBillNumber || invoice.invoiceNumber}`)}`;
  const qrImageSrc = `https://api.qrserver.com/v1/create-qr-code/?size=130x130&data=${encodeURIComponent(upiPayUrl)}`;

  return (
    <div className="fixed inset-0 z-50 bg-slate-900/80 backdrop-blur-xs flex items-center justify-center p-2 sm:p-4 overflow-y-auto print:p-0 print:bg-white">
      
      {/* Container Dialog */}
      <div className="bg-white rounded-xl shadow-2xl max-w-4xl w-full border border-slate-300 overflow-hidden my-auto max-h-[96vh] flex flex-col print:max-w-none print:w-full print:border-none print:shadow-none print:m-0 print:rounded-none">
        
        {/* Top Floating Control Bar (Hidden on Print) */}
        <div className="bg-slate-900 text-white px-4 py-2.5 flex items-center justify-between print:hidden shrink-0">
          <div className="flex items-center space-x-3">
            <span className="text-xs font-bold uppercase tracking-wider text-slate-300">
              Tax Invoice Print Preview
            </span>
            <div className="flex bg-slate-800 rounded p-0.5 border border-slate-700 text-xs">
              {(['Original', 'Duplicate', 'Triplicate'] as const).map(type => (
                <button
                  key={type}
                  onClick={() => setCopyType(type)}
                  className={`px-2.5 py-1 rounded text-[11px] font-bold transition-all ${
                    copyType === type ? 'bg-blue-600 text-white shadow-xs' : 'text-slate-400 hover:text-slate-200'
                  }`}
                >
                  {type}
                </button>
              ))}
            </div>
          </div>

          <div className="flex items-center space-x-2">
            <button
              onClick={handleCopySummary}
              className="flex items-center space-x-1 bg-slate-800 hover:bg-slate-700 text-slate-200 px-2.5 py-1.5 rounded text-xs font-semibold border border-slate-700 transition-colors"
            >
              {copied ? <Check className="w-3.5 h-3.5 text-green-400" /> : <Copy className="w-3.5 h-3.5" />}
              <span>{copied ? 'Copied' : 'Copy Text'}</span>
            </button>

            <button
              onClick={handlePrint}
              className="flex items-center space-x-1.5 bg-blue-600 hover:bg-blue-700 text-white px-4 py-1.5 rounded text-xs font-bold shadow-xs transition-colors"
            >
              <Printer className="w-3.5 h-3.5" />
              <span>Print A4 Invoice</span>
            </button>

            <button
              onClick={onClose}
              className="text-slate-400 hover:text-white p-1 rounded transition-colors"
            >
              <X className="w-5 h-5" />
            </button>
          </div>
        </div>

        {/* Printable Paper Area */}
        <div className="p-4 sm:p-6 overflow-y-auto bg-slate-100 print:bg-white print:p-0 flex-1">
          <div className="bg-white p-6 sm:p-8 max-w-3xl mx-auto shadow-md border border-slate-300 print:border-none print:shadow-none print:p-0 print:m-0 text-slate-900 text-[12px] leading-tight font-sans">
            
            {/* Header: Company & Title */}
            <div className="border border-slate-800">
              
              {/* Copy Label & GST Title */}
              <div className="border-b border-slate-800 px-3 py-1 flex items-center justify-between bg-slate-100 font-bold text-[11px]">
                <span className="text-slate-600 uppercase tracking-widest">
                  GSTIN: {settings.gstin}
                </span>
                <span className="text-slate-900 font-black uppercase text-xs">
                  TAX INVOICE / SALES BILL
                </span>
                <span className="text-slate-800 uppercase font-mono text-[10px]">
                  ({copyType.toUpperCase()} FOR {copyType === 'Original' ? 'RECIPIENT' : copyType === 'Duplicate' ? 'TRANSPORTER' : 'SUPPLIER'})
                </span>
              </div>

              {/* Company Profile Header */}
              <div className="p-3 text-center border-b border-slate-800 space-y-0.5">
                <h1 className="text-lg font-black tracking-tight text-slate-900 uppercase">
                  {settings.companyName}
                </h1>
                <p className="text-[11px] font-semibold text-slate-700">{settings.tagline}</p>
                <p className="text-[11px] text-slate-600">
                  {settings.address}, {settings.city}, {settings.state} - {settings.pincode}
                </p>
                <p className="text-[11px] font-medium text-slate-600">
                  Phone: <strong className="text-slate-900">{settings.phone}</strong> {settings.alternatePhone && `| ${settings.alternatePhone}`} | Email: {settings.email}
                </p>
                <p className="text-[11px] font-mono font-bold text-slate-800">
                  PAN: {settings.pan} | State: {settings.state} (Code: 27)
                </p>
              </div>

              {/* Invoice Meta Grid */}
              <div className="grid grid-cols-2 border-b border-slate-800 divide-x divide-slate-800">
                <div className="p-2 space-y-1">
                  <div className="flex justify-between">
                    <span className="text-slate-500 font-semibold">Invoice / Bill No:</span>
                    <strong className="font-mono text-slate-900 font-bold">{invoice.salesBillNumber || invoice.invoiceNumber}</strong>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-slate-500 font-semibold">Invoice Date:</span>
                    <span className="font-mono">{invoice.salesBillDate || invoice.invoiceDate}</span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-slate-500 font-semibold">Due Date:</span>
                    <span className="font-mono">{invoice.dueDate || 'Immediate'}</span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-slate-500 font-semibold">State of Supply:</span>
                    <span>{invoice.consignorState || 'Maharashtra'} ({invoice.consignorStateCode || '27'})</span>
                  </div>
                </div>

                <div className="p-2 space-y-1">
                  <div className="flex justify-between">
                    <span className="text-slate-500 font-semibold">Transport / Vehicle No:</span>
                    <strong className="font-mono uppercase">{invoice.vehicleNumber || '—'}</strong>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-slate-500 font-semibold">Bilty / LR No:</span>
                    <span className="font-mono">{invoice.lrNumber || '—'}</span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-slate-500 font-semibold">E-Way Bill No:</span>
                    <span className="font-mono">{invoice.salesBillNumber ? invoice.lrNumber : '—'}</span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-slate-500 font-semibold">Reverse Charge (RCM):</span>
                    <span className="font-bold">{invoice.taxMechanism === 'rcm' ? 'YES' : 'NO'}</span>
                  </div>
                </div>
              </div>

              {/* Billed To & Shipped To */}
              <div className="grid grid-cols-2 border-b border-slate-800 divide-x divide-slate-800 bg-slate-50/50">
                {/* Details of Receiver (Billed To) */}
                <div className="p-2.5 space-y-1">
                  <div className="text-[10px] font-bold uppercase tracking-wider text-slate-500 mb-1 border-b border-slate-200 pb-0.5">
                    Details of Receiver / Billed To:
                  </div>
                  <div className="font-bold text-slate-900 text-xs">
                    {invoice.consignorName || invoice.consigneeName}
                  </div>
                  <div className="text-[11px] text-slate-700 leading-tight">
                    {invoice.consignorAddress || invoice.consigneeAddress || 'N/A'}
                  </div>
                  <div className="text-[11px]">
                    <span className="text-slate-500">GSTIN / UIN: </span>
                    <strong className="font-mono text-slate-900">{invoice.consignorGSTIN || invoice.consigneeGSTIN || 'URP (Unregistered)'}</strong>
                  </div>
                  <div className="text-[11px]">
                    <span className="text-slate-500">State: </span>
                    <span>{invoice.consignorState || 'Maharashtra'} (Code: {invoice.consignorStateCode || '27'})</span>
                  </div>
                </div>

                {/* Details of Consignee (Shipped To) */}
                <div className="p-2.5 space-y-1">
                  <div className="text-[10px] font-bold uppercase tracking-wider text-slate-500 mb-1 border-b border-slate-200 pb-0.5">
                    Details of Consignee / Shipped To:
                  </div>
                  <div className="font-bold text-slate-900 text-xs">
                    {invoice.shipToName || invoice.consigneeName || invoice.consignorName}
                  </div>
                  <div className="text-[11px] text-slate-700 leading-tight">
                    {invoice.shipToAddress || invoice.consigneeAddress || invoice.consignorAddress || 'Same as Billed Address'}
                  </div>
                  <div className="text-[11px]">
                    <span className="text-slate-500">GSTIN / UIN: </span>
                    <strong className="font-mono text-slate-900">{invoice.shipToGSTIN || invoice.consigneeGSTIN || invoice.consignorGSTIN || 'URP'}</strong>
                  </div>
                  <div className="text-[11px]">
                    <span className="text-slate-500">State: </span>
                    <span>{invoice.shipToState || invoice.consigneeState || invoice.consignorState || 'Maharashtra'}</span>
                  </div>
                </div>
              </div>

              {/* Product Line Items Table */}
              <div className="overflow-x-auto">
                <table className="w-full text-left text-[11px] border-collapse">
                  <thead>
                    <tr className="bg-slate-100 font-bold border-b border-slate-800 text-slate-900">
                      <th className="p-1.5 border-r border-slate-800 text-center w-8">#</th>
                      <th className="p-1.5 border-r border-slate-800">Description of Goods / Services</th>
                      <th className="p-1.5 border-r border-slate-800 text-center">HSN/SAC</th>
                      <th className="p-1.5 border-r border-slate-800 text-right">Qty</th>
                      <th className="p-1.5 border-r border-slate-800 text-center">Unit</th>
                      <th className="p-1.5 border-r border-slate-800 text-right">Rate (₹)</th>
                      <th className="p-1.5 border-r border-slate-800 text-right">Taxable Amt (₹)</th>
                      <th className="p-1.5 border-r border-slate-800 text-center">GST %</th>
                      <th className="p-1.5 text-right">Total (₹)</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-slate-300">
                    {invoice.items && invoice.items.length > 0 ? (
                      invoice.items.map((item, idx) => {
                        const slab = item.gstRate !== undefined ? item.gstRate : invoice.taxSlab;
                        const rate = item.rate || (item.ratePerTon ?? (item.amount / item.quantity));
                        const taxable = item.taxableAmount || (item.quantity * rate);
                        const taxAmt = (taxable * slab) / 100;
                        const totalWithTax = taxable + taxAmt;

                        return (
                          <tr key={item.id || idx}>
                            <td className="p-1.5 border-r border-slate-800 text-center font-mono">{idx + 1}</td>
                            <td className="p-1.5 border-r border-slate-800 font-semibold">{item.description}</td>
                            <td className="p-1.5 border-r border-slate-800 text-center font-mono">{item.hsnCode || '—'}</td>
                            <td className="p-1.5 border-r border-slate-800 text-right font-mono font-bold">{item.quantity}</td>
                            <td className="p-1.5 border-r border-slate-800 text-center">{item.unit || 'Bags'}</td>
                            <td className="p-1.5 border-r border-slate-800 text-right font-mono">₹{formatINR(rate)}</td>
                            <td className="p-1.5 border-r border-slate-800 text-right font-mono font-bold">₹{formatINR(taxable)}</td>
                            <td className="p-1.5 border-r border-slate-800 text-center font-bold font-mono">{slab}%</td>
                            <td className="p-1.5 text-right font-mono font-bold">₹{formatINR(totalWithTax)}</td>
                          </tr>
                        );
                      })
                    ) : (
                      <tr>
                        <td className="p-1.5 border-r border-slate-800 text-center font-mono">1</td>
                        <td className="p-1.5 border-r border-slate-800 font-semibold">{invoice.materialType || 'Goods Transport & Supply'}</td>
                        <td className="p-1.5 border-r border-slate-800 text-center font-mono">996511</td>
                        <td className="p-1.5 border-r border-slate-800 text-right font-mono font-bold">1</td>
                        <td className="p-1.5 border-r border-slate-800 text-center">Lot</td>
                        <td className="p-1.5 border-r border-slate-800 text-right font-mono">₹{formatINR(invoice.subTotal)}</td>
                        <td className="p-1.5 border-r border-slate-800 text-right font-mono font-bold">₹{formatINR(invoice.subTotal)}</td>
                        <td className="p-1.5 border-r border-slate-800 text-center font-bold font-mono">{invoice.taxSlab}%</td>
                        <td className="p-1.5 text-right font-mono font-bold">₹{formatINR(invoice.grandTotal)}</td>
                      </tr>
                    )}
                  </tbody>
                </table>
              </div>

              {/* Rate-Wise GST Summary Table (HSN Breakdown) */}
              <div className="border-t border-slate-800">
                <div className="bg-slate-100 px-2 py-1 font-bold text-[10px] text-slate-800 uppercase tracking-wider border-b border-slate-800">
                  GST Rate-Wise Tax Summary Breakdown
                </div>
                <table className="w-full text-[10px] border-collapse">
                  <thead>
                    <tr className="bg-slate-50 border-b border-slate-800 text-slate-700 font-bold">
                      <th className="p-1 border-r border-slate-800">HSN/SAC</th>
                      <th className="p-1 border-r border-slate-800 text-right">Taxable Value (₹)</th>
                      {!isInterState ? (
                        <>
                          <th className="p-1 border-r border-slate-800 text-center">CGST %</th>
                          <th className="p-1 border-r border-slate-800 text-right">CGST Amt (₹)</th>
                          <th className="p-1 border-r border-slate-800 text-center">SGST %</th>
                          <th className="p-1 border-r border-slate-800 text-right">SGST Amt (₹)</th>
                        </>
                      ) : (
                        <>
                          <th className="p-1 border-r border-slate-800 text-center">IGST %</th>
                          <th className="p-1 border-r border-slate-800 text-right">IGST Amt (₹)</th>
                        </>
                      )}
                      <th className="p-1 text-right">Total Tax (₹)</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-slate-200">
                    {gstRateSummaries.length > 0 ? (
                      gstRateSummaries.map((summary, sIdx) => (
                        <tr key={sIdx} className="font-mono">
                          <td className="p-1 border-r border-slate-800 text-center font-bold">{summary.hsnCode}</td>
                          <td className="p-1 border-r border-slate-800 text-right">₹{formatINR(summary.taxableValue)}</td>
                          {!isInterState ? (
                            <>
                              <td className="p-1 border-r border-slate-800 text-center">{summary.cgstRate}%</td>
                              <td className="p-1 border-r border-slate-800 text-right">₹{formatINR(summary.cgstAmount)}</td>
                              <td className="p-1 border-r border-slate-800 text-center">{summary.sgstRate}%</td>
                              <td className="p-1 border-r border-slate-800 text-right">₹{formatINR(summary.sgstAmount)}</td>
                            </>
                          ) : (
                            <>
                              <td className="p-1 border-r border-slate-800 text-center">{summary.igstRate}%</td>
                              <td className="p-1 border-r border-slate-800 text-right">₹{formatINR(summary.igstAmount)}</td>
                            </>
                          )}
                          <td className="p-1 text-right font-bold">₹{formatINR(summary.totalTax)}</td>
                        </tr>
                      ))
                    ) : (
                      <tr className="font-mono">
                        <td className="p-1 border-r border-slate-800 text-center font-bold">996511</td>
                        <td className="p-1 border-r border-slate-800 text-right">₹{formatINR(invoice.subTotal)}</td>
                        {!isInterState ? (
                          <>
                            <td className="p-1 border-r border-slate-800 text-center">{invoice.cgstRate}%</td>
                            <td className="p-1 border-r border-slate-800 text-right">₹{formatINR(invoice.cgstAmount)}</td>
                            <td className="p-1 border-r border-slate-800 text-center">{invoice.sgstRate}%</td>
                            <td className="p-1 border-r border-slate-800 text-right">₹{formatINR(invoice.sgstAmount)}</td>
                          </>
                        ) : (
                          <>
                            <td className="p-1 border-r border-slate-800 text-center">{invoice.igstRate}%</td>
                            <td className="p-1 border-r border-slate-800 text-right">₹{formatINR(invoice.igstAmount)}</td>
                          </>
                        )}
                        <td className="p-1 text-right font-bold">₹{formatINR(invoice.totalTax)}</td>
                      </tr>
                    )}
                  </tbody>
                </table>
              </div>

              {/* Total Calculation Matrix */}
              <div className="grid grid-cols-2 border-t border-slate-800 divide-x divide-slate-800">
                
                {/* Left Side: Amount in words & Bank info */}
                <div className="p-2.5 space-y-2 flex flex-col justify-between">
                  <div>
                    <div className="text-[10px] text-slate-500 font-bold uppercase">Invoice Total (in words):</div>
                    <div className="font-bold text-slate-900 text-xs italic mt-0.5">
                      {numberToWordsINR(invoice.grandTotal)}
                    </div>
                  </div>

                  {/* Bank Details & QR Code */}
                  <div className="border border-slate-300 rounded p-2 bg-slate-50 text-[10px] space-y-0.5">
                    <div className="font-bold text-slate-900 uppercase flex items-center justify-between border-b border-slate-200 pb-0.5">
                      <span>Bank Account Details for Payment</span>
                      <span className="font-mono text-[9px] text-blue-700">UPI / IMPS / NEFT</span>
                    </div>
                    <div>Bank Name: <strong>{settings.bankName}</strong></div>
                    <div>A/C Number: <strong className="font-mono">{settings.bankAccountNo}</strong></div>
                    <div>IFSC Code: <strong className="font-mono">{settings.bankIfsc}</strong></div>
                    <div>Branch: {settings.bankBranch}</div>
                    {settings.upiId && <div>UPI ID: <strong className="font-mono text-emerald-700">{settings.upiId}</strong></div>}
                  </div>
                </div>

                {/* Right Side: Totals breakdown */}
                <div className="p-2 space-y-1 text-xs">
                  <div className="flex justify-between py-0.5">
                    <span className="text-slate-600">Subtotal (Taxable Value):</span>
                    <span className="font-mono font-semibold">₹{formatINR(invoice.subTotal)}</span>
                  </div>

                  {!isInterState ? (
                    <>
                      <div className="flex justify-between py-0.5">
                        <span className="text-slate-600">CGST Amount:</span>
                        <span className="font-mono font-semibold">₹{formatINR(invoice.cgstAmount)}</span>
                      </div>
                      <div className="flex justify-between py-0.5">
                        <span className="text-slate-600">SGST Amount:</span>
                        <span className="font-mono font-semibold">₹{formatINR(invoice.sgstAmount)}</span>
                      </div>
                    </>
                  ) : (
                    <div className="flex justify-between py-0.5">
                      <span className="text-slate-600">IGST Amount:</span>
                      <span className="font-mono font-semibold">₹{formatINR(invoice.igstAmount)}</span>
                    </div>
                  )}

                  {invoice.loadingCharges > 0 && (
                    <div className="flex justify-between py-0.5">
                      <span className="text-slate-600">Freight / Transport:</span>
                      <span className="font-mono font-semibold">₹{formatINR(invoice.loadingCharges)}</span>
                    </div>
                  )}

                  {invoice.otherCharges > 0 && (
                    <div className="flex justify-between py-0.5">
                      <span className="text-slate-600">Other Charges:</span>
                      <span className="font-mono font-semibold">₹{formatINR(invoice.otherCharges)}</span>
                    </div>
                  )}

                  {invoice.roundOff !== undefined && invoice.roundOff !== 0 && (
                    <div className="flex justify-between py-0.5 text-slate-500">
                      <span>Round Off:</span>
                      <span className="font-mono">₹{formatINR(invoice.roundOff)}</span>
                    </div>
                  )}

                  <div className="flex justify-between py-1.5 border-t-2 border-slate-800 text-sm font-black text-slate-900 bg-slate-100 px-1.5 rounded">
                    <span>GRAND TOTAL (₹):</span>
                    <span className="font-mono">₹{formatINR(invoice.grandTotal)}</span>
                  </div>

                  {invoice.amountPaid > 0 && (
                    <div className="flex justify-between py-0.5 text-emerald-700 font-bold text-[11px]">
                      <span>Advance / Paid:</span>
                      <span className="font-mono">(-) ₹{formatINR(invoice.amountPaid)}</span>
                    </div>
                  )}

                  {invoice.balanceDue > 0 && (
                    <div className="flex justify-between py-1 border-t border-dashed border-slate-300 text-xs font-black text-rose-700">
                      <span>BALANCE PAYABLE:</span>
                      <span className="font-mono">₹{formatINR(invoice.balanceDue)}</span>
                    </div>
                  )}
                </div>

              </div>

              {/* Bottom Terms & Signatures */}
              <div className="grid grid-cols-2 border-t border-slate-800 divide-x divide-slate-800 text-[10px]">
                <div className="p-2.5 space-y-1">
                  <div className="font-bold text-slate-800 uppercase tracking-wider">Terms & Conditions:</div>
                  <ol className="list-decimal list-inside text-slate-600 space-y-0.5">
                    {settings.termsAndConditions?.slice(0, 3).map((term, tIdx) => (
                      <li key={tIdx} className="leading-tight">{term}</li>
                    )) || <li>Subject to local jurisdiction.</li>}
                  </ol>
                </div>

                <div className="p-2.5 flex flex-col justify-between items-end text-right h-24">
                  <div className="font-bold text-slate-900">
                    For <span className="uppercase">{settings.companyName}</span>
                  </div>
                  <div className="text-[10px] text-slate-500 font-semibold border-t border-slate-400 pt-1 w-44 text-center">
                    Authorized Signatory
                  </div>
                </div>
              </div>

            </div>

            {/* Footer Notice */}
            <div className="text-center text-[9px] text-slate-500 mt-2 font-mono">
              This is a computer generated invoice and does not require physical signature under GST rules.
            </div>

          </div>
        </div>

      </div>

    </div>
  );
};
